### ISSUE TITLE
Setup Script

### ISSUE THREAD

**Issue by jakehamilton** [jakehamilton/dotfiles#2]
The project should offer a setup script that, when run, will move all of the required files to their appropriate places. This would greatly reduce time spent when trying to install everything.

**Comment by circleous** [comment]
use `GNU stow` that'll help alot

**Comment by jakehamilton** [comment]
@circleous, sounds like the right tool for the job. I've sort of left this repo and focused my efforts elsewhere (work and occasionally leverage). I'm actually not even on Linux for my daily driver so any contributions may have to come from anyone else who is interested.

**Comment by jakehamilton** [comment]
Fixed now that packages are separated to make `stow $package` possible.
